### PR TITLE
Deliverable 1 Transit Equity Team 1

### PR DESCRIPTION
**Pull request by jamie-dc**
## Description of Change

Adding Deliverable 1 and related files

## Team Name and Contributers

Transit Equity Team 1
Jun Li, Jun Hao Lei, Kenneth Lin, Jamie Dela Cruz

## Checklist

Before creating your PR, please ensure the following requirements.

### General

- [x] PR does **not** include irrelevant or hidden files (i.e. `__pycache__`, `.vscode`... etc.)
- [x] Changes are in the correct folder
- [x] There are no merge conflicts
- [x] Commit messages are sensible and descriptive

### Code

- [x] Implementation matches proposed design
- [x] Documentation on how to run the code is created/updated
- [x] Code is legible

### Report

- [x] Report meets the deliverable criteria
- [x] Proposal is up to date with latest decisions

### CODE REVIEW

**Comment by stevebackman** [comment]
Hey gang, when I look at the posted census.csv, I don't see column for
income.
I wonder if I can take a look at the file as extracted for project.

(Sorry for not cc'ing whole team.)

Steve

**Comment by stevebackman** [comment]
I should have said, want to look at the mysterious income figures.

**Comment by jamie-dc** [comment]
What were you wanting to take a look at? The source of the median household
income data?

**Comment by stevebackman** [comment]
The source of median household income data is from https://api.census.gov,
specifically
https://api.census.gov/data/2018/acs/acs5?get=B19013_001E&for=tract:*&in=state:25.
A groupmate was able to relocate it at
https://www.census.gov/data/developers/data-sets/acs-1year.2018.html, but
I'm still waiting on his response as to how he was able to find this
specific data.

**Comment by stevebackman** [comment]
Yes. I just see "census.csv,"

**Pull request merged**
